konten/urls.py
from django.urls import path
from . import views

app_name = "konten"

urlpatterns = [
    path("", views.viewKonten, name="listKonten"),
    path("add", views.addKonten, name="addKonten"),
    path("delete/<int:id>", views.deleteKonten, name="deleteKonten"),
    path("publish/<int:id>", views.publishKonten, name="publishKonten"),
]

kursus_plus/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("users.urls")),
    path("session/", include("video_call.urls")),
    path("courses/", include("courses.urls")),
    path("konten/", include("konten.urls")),
    path("dashboard/", include("dashboard.urls")),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("", views.landing, name="landing"),
    path("login", views.login_view, name="login"),
    path("register", views.register, name="register"),
    path("profile", views.profile, name="profile"),
    path("edit", views.edit, name="edit"),
    path("logout", views.logout_view, name="logout"),
    path("saldo/", views.saldo, name="saldo"),
]

konten/models.py
from django.db import models
from django.contrib.auth.models import User
import uuid

# Create your models here.
class KontenKreatif(models.Model):
    id = models.AutoField(primary_key=True)
    isPublished = models.BooleanField(default=False)
    tanggalPublish = models.DateTimeField()
    judul = models.CharField(max_length=50)
    isi = models.TextField()
    tanggalPenulisan = models.DateTimeField(auto_now_add=True, editable=False)
    penulis = models.ForeignKey(
        'users.KontenKreator',
        on_delete=models.CASCADE
    )
    
    def publish(self):
        self.isPublished = True

    def __str__(self):
        return self.judul

konten/views.py
from django.shortcuts import render, redirect
from django.utils import timezone
from django.forms import ValidationError
from .models import KontenKreatif
from users.models import KontenKreator
from django.contrib import messages

import datetime

month = ['Januari', 'Februari', 'Maret', 'April', 'Mei', 'Juni', 'Juli', 'Agustus', 'September', 'Oktober', 'November', 'Desember']

# Create your views here.
def viewKonten(request):
    user = request.user
    currentDate = datetime.datetime.now(tz=timezone.get_current_timezone())
    context = {"konten" : KontenKreatif.objects.filter(isPublished=True), "kreator" : user.is_authenticated and KontenKreator.objects.filter(user=user).count() == 1 or user.is_superuser}
    for konten in context["konten"]:
        konten.tanggalPublish = str(konten.tanggalPublish.day) + ' ' + str(month[konten.tanggalPublish.month-1]) + ' ' + str(konten.tanggalPublish.year)
        if not request.user.is_authenticated:
            konten.isi = konten.isi[:300]
    for konten in KontenKreatif.objects.all():
        thisKonten = KontenKreatif.objects.filter(id=konten.id)
        if context["kreator"]:
            if KontenKreator.objects.get(user=request.user).id == konten.penulis.id or request.user.is_superuser and konten.isPublished == False:
                context["konten"] |= thisKonten
        if konten.tanggalPublish <= currentDate and konten.isPublished == False:
            konten.publish()
            konten.save()
            context["konten"] |= thisKonten
    return render(request, "viewKonten.html", context)


def addKonten(request):
    user = request.user
    KontenKreators = KontenKreator.objects.all()
    context = {"kreator" : user.is_authenticated and KontenKreator.objects.filter(user=user).count() == 1 or user.is_superuser}

    if request.method == 'POST':
        penuliss = KontenKreator.objects.filter(user = user)[:1]
        penulis = penuliss[0]

        judul = request.POST.get('judul')
        isi = request.POST.get('isi')
        tanggalPublish = request.POST.get('tanggalPublish')

        try: 
            kontenKreatif = KontenKreatif.objects.create(tanggalPublish = tanggalPublish, judul = judul, \
            isi = isi, penulis = penulis)
            kontenKreatif.save()
        except ValidationError:
            messages.error(request, "Terdapat kesalahan dalam pengisian formulir, silahkan isi ulang formulir!")

            return render(request, "addKonten.html", context)

        messages.success(request, "Konten berhasil ditambahkan")

        return redirect("konten:listKonten")

    return render(request, "addKonten.html", context)

def deleteKonten(request, id):
    user = request.user
    objectKonten = KontenKreatif.objects.get(id = id)
    penuliss = KontenKreator.objects.filter(user = user)[:1]
    penulis = penuliss[0]

    if penulis.user == user:
        objectKonten.delete()
        messages.success(request, "Konten berhasil dihapus")

        return redirect("konten:listKonten")
    
    messages.error(request, "Konten tidak berhasil dihapus")

    return redirect("konten:listKonten")

def publishKonten(request, id):
    user = request.user
    objectKonten = KontenKreatif.objects.get(id = id)
    penuliss = KontenKreator.objects.filter(user = user)[:1]
    penulis = penuliss[0]

    if penulis.user == user:
        objectKonten.publish()
        objectKonten.save()
        messages.success(request, "Konten berhasil publish")

        return redirect("konten:listKonten")

    messages.error(request, "Konten tidak berhasil dipublish")

    return redirect("konten:listKonten")

konten/templates/addKonten.html
{% extends 'users/base.html' %}
{% block content %}

{% if kreator and not user.is_superuser%}
    <!-- Flash Field -->
    {% if messages %}
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
    {% for message in messages %}
        {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    {% endfor %}
    </div>
    {% endif %}

    <!-- Content Form -->
    <div class="col-lg-12">

        <div class="container">
            <div class="bg-5 border-2 p-3 rounded my-2">
                <h3 class="text-center">Konten Kreatif</h3>
        
                <form class="d-flex flex-column justify-content-center" action="#" method="POST">
                    {% csrf_token %}
                    <div class="form-group">

                        <div class="mb-3">
                            <label for="title" class="form-label">Judul</label>
                            <input type="text" class="form-control" id="inputJudul" placeholder="Judul" name="judul">
                        </div>
        
                        <div class="mb-3">
                            <label for="contentText" class="form-label">Isi</label>
                            <textarea class="form-control" id="inputIsi" rows="20" placeholder="Lorem Ipsum ..." name="isi"></textarea>
                        </div>

                        <div class="mb-3">
                            <label for="publish" class="form-label">Tanggal Publish</label>
                            <input class="form-control" type="date" id="publishDate" name="tanggalPublish">
                        </div>
        
                        <button type="submit" class="btn btn-block btn-1 border-2">Submit</button>
                    </div>
                </form>
            </div>
        </div>

    
    </div>

{% else %}
<div class="col-lg-12">

    <div class="container">
        <div class="bg-5 border-2 p-3 rounded my-2">
            <h3 class="text-center">User tidak mempunyai akses untuk menambah konten!</h3>
            <h3 class="text-center"><a class="nav-link text-dark" href="{% url 'konten:listKonten' %}"><u>Kembali ke Konten</u></a></h3>
        </div>
    </div>
    </div>
{% endif %}
{% endblock %}

konten/templates/viewKonten.html
{% extends 'users/base.html' %}
{% load static %}
{% block content %}
<!-- MODAL area -->
<link rel="stylesheet" href="{% static 'konten/css/konten.css' %}">

<!-- Flash Field -->
{% if messages %}
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  {% for message in messages %}
    {{ message }}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  {% endfor %}
</div>
{% endif %}

{% if kreator and not user.is_superuser%}
<button type="button" onclick="window.location.href='./add';" class="btn btn-success btn-block">Tambah Konten Baru</button>
{% endif %}

{% for kontens in konten %}
<div class="modal fade" id="confirmDelete{{kontens.id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header bg-1 text-light">
          <h5 class="modal-title" id="exampleModalLongTitle">Konfirmasi Penghapusan</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>

        <div class="modal-body bg-5 text-center">
          <b>
              Apakah anda yakin untuk menghapus konten tersebut? Konten yang sudah dihapus <u>tidak dapat dipulihkan kembali</u>!
          </b>
        </div>

        <div class="modal-footer bg-1 d-flex justify-content-center">
        <form method="POST" action="{% url 'konten:deleteKonten' kontens.id %}">
            {% csrf_token %}
          <button type="submit" class="btn btn-success">DELETE</button>
        </form>
          <button type="button" class="btn btn-danger" data-dismiss="modal">CANCEL</button>
        </div>
      </div>
    </div>
  </div>

  <div class="modal fade" id="confirmPublish{{kontens.id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header bg-1 text-light">
          <h5 class="modal-title" id="exampleModalLongTitle">Konfirmasi Publish</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>

        <div class="modal-body bg-5 text-center">
          <b>
              Apakah anda yakin untuk mempublish konten tersebut? Tanggal publish yang ditentukan sebelumnya akan <u>diabaikan</u> oleh sistem!
          </b>
        </div>

        <div class="modal-footer bg-1 d-flex justify-content-center">
        <form method="POST" action="{% url 'konten:publishKonten' kontens.id %}">
            {% csrf_token %}
          <button type="submit" class="btn btn-success">PUBLISH</button>
        </form>
          <button type="button" class="btn btn-danger" data-dismiss="modal">CANCEL</button>
        </div>
      </div>
    </div>
  </div>

<!-- HTML AREA -->
<div class="row">
  
    <div class="col-lg-12">
        <div class="bg-5 border-1 p-3 rounded my-2">
            <!-- Sementara judul dan tanggal publish begini dulu, mungkin lebih bagus klo pake d-flex -->
            <div class="row">
                <div class="col-lg-4">
                    <h1>{{kontens.judul}}</h1>
                </div>
                <div class="col-lg-4">
                    <p>
                        dipublish pada {{kontens.tanggalPublish}}<br>
                        ditulis oleh {{kontens.penulis.nama}}
                    </p>
                </div>
            </div>

            <div>
                <p class="mt-3">
                      {{kontens.isi}}
                      {% if not user.is_authenticated %}
                        ..<a href="{% url 'users:login' %}">Login untuk baca lebih lanjut</a>
                      {% endif %}
                    
                </p>
            </div>

            {% if user.is_authenticated and user.id == kontens.penulis.user.id or user.is_superuser%}  
            <div class="row">
              {% if kontens.isPublished == True %}
                <div class="col-md-12">
                    <button type="button" class="btn btn-del w-100" data-toggle="modal" data-target="#confirmDelete{{kontens.id}}">Hapus</button>
                </div>
              {% else %}
                <div class="col-md-6">
                    <button type="button" class="btn btn-del w-100" data-toggle="modal" data-target="#confirmDelete{{kontens.id}}">Hapus</button>
                </div>
                <div class="col-md-6">
                    <button type="button" class="btn w-100 btn-primary" data-toggle="modal" data-target="#confirmPublish{{kontens.id}}">Publish Sekarang</button>
                </div>
              {% endif %}
    
            </div>
            {% endif %}

        </div>
    </div>
</div>
{% endfor %}

{% endblock %}