courses/urls.py
from django.urls import path
from . import views

app_name = "courses"

urlpatterns = [
    path("", views.courses_list, name="courses_list"),
    path("<int:course_id>/subcourses", views.subcourses_list, name="subcourses_list"),
    path("subcourses/<int:subcourse_id>", views.subcourses_detail, name="subcourse_detail"),
    path("subcourses/<int:subcourse_id>/checkout", views.checkout, name="checkout"),
]

dashboard/urls.py
from django.urls import path
from . import views

app_name = "dashboard"

urlpatterns = [
    path("", views.upcoming, name="upcoming")
]

konten/urls.py
from django.urls import path
from . import views

app_name = "konten"

urlpatterns = [
    path("", views.viewKonten, name="listKonten"),
    path("add", views.addKonten, name="addKonten"),
    path("delete/<int:id>", views.deleteKonten, name="deleteKonten"),
    path("publish/<int:id>", views.publishKonten, name="publishKonten"),
]

kursus_plus/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("users.urls")),
    path("session/", include("video_call.urls")),
    path("courses/", include("courses.urls")),
    path("konten/", include("konten.urls")),
    path("dashboard/", include("dashboard.urls")),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("", views.landing, name="landing"),
    path("login", views.login_view, name="login"),
    path("register", views.register, name="register"),
    path("profile", views.profile, name="profile"),
    path("edit", views.edit, name="edit"),
    path("logout", views.logout_view, name="logout"),
    path("saldo/", views.saldo, name="saldo"),
]

users/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime, timedelta
from courses.models import Subcourse, Appointment, Transaksi
from uuid import uuid4

class StudentProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    deskripsi = models.TextField(default="Halo! Saya siap belajar.")
    nama = models.CharField(max_length=255, default="Anonim")
    foto_profil = models.URLField(default="https://upload.wikimedia.org/wikipedia/commons/8/89/Portrait_Placeholder.png")
    bidang_minat = models.CharField(max_length=255, default="-")
    saldo = models.IntegerField(default=0)

    def edit_profil(self, deskripsi=None, foto_profil=None, bidang_minat=None):
        if deskripsi:
            self.deskripsi = deskripsi

        if foto_profil:
            self.foto_profil = foto_profil

        if bidang_minat:
            self.bidang_minat = bidang_minat

        self.save()

    def get_upcoming_apt(self):
        return Appointment.objects.filter(
            bagian_dari__student_pembeli=self,
            waktu_kursus__gte=datetime.now()
        )

    def beli(self, subcourse_dibeli):
        self.saldo -= subcourse_dibeli.harga
        self.save()

        # Buat instance Transakdi
        new_transaksi = Transaksi.objects.create(
            metode_pembayaran="Saldo",
            jumlah_pembayaran=subcourse_dibeli.harga,
            student_pembeli=self,
            subcourse_dibeli=subcourse_dibeli,
            status="Sukses"
        )

        # Buat instance Appointment
        for ii in range(subcourse_dibeli.jam_dibutuhkan):
            Appointment.objects.create(
                status="Pending",
                waktu_kursus=datetime.now() + timedelta(days=ii+1,minutes=30),
                kode_video_call=str(uuid4()),
                bagian_dari=new_transaksi
            )

    def isi_saldo(self, saldo_dibeli):
        self.saldo += saldo_dibeli
        self.save()

    def get_nama(self):
        return self.nama

class KontenKreator(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    nama = models.CharField(max_length=255, default="Anonim")

    def __str__(self):
        return self.nama

users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth import authenticate
from django.contrib import messages
from django.contrib.auth import login, logout, authenticate

from users.models import StudentProfile


# Create your views here.
def landing(request):
    if request.user.is_authenticated:
        return redirect("dashboard:upcoming")

    return render(request, "users/landing.html")

def logout_view(request):
    if request.user.is_authenticated:
        logout(request)
    return redirect("users:landing")

def login_view(request):
    if request.user.is_authenticated:
        return redirect("dashboard:upcoming")
    

    if request.method == "POST":
        user = authenticate(
            username = request.POST.get("username", None),
            password = request.POST.get("password", None)
        )

        if user is not None:
            login(request, user)
            return redirect("dashboard:upcoming")

        else:
            messages.add_message(request, messages.WARNING, f"Username atau password salah.")

    return render(request, "users/login.html")

def register(request):
    if request.user.is_authenticated:
        return redirect("dashboard:upcoming")

    if request.method == "POST":
        if (request.POST["password1"] != request.POST["password2"]):
            messages.add_message(request, messages.WARNING, "Password di kedua input tidak sama!")
        elif User.objects.filter(username=request.POST["username"]):
            messages.add_message(request, messages.WARNING, "Username sudah terdaftar, silahkan login atau ambil username lain")
        else: # Case sukses register
            
            new_user = User.objects.create_user(
                request.POST["username"],
                password=request.POST["password1"],
                email=request.POST["email"]    
            )

            new_user.save()

            # Bikin profile baru
            StudentProfile.objects.create(
                user = new_user,
                nama = request.POST["username"],
            )


            messages.add_message(request, messages.SUCCESS, "Pendaftaran sukses, silahkan login.")
            return redirect("users:login")

            
    return render(request, "users/register.html")

def profile(request):
    if not request.user.is_authenticated:
        return redirect("users:login")
    user = StudentProfile.objects.get(user=request.user.id)
    context = {"user" : user}
    return render(request, "users/profile.html", context)

def edit(request):
    if not request.user.is_authenticated:
        return redirect("users:login")
    user = StudentProfile.objects.get(user=request.user.id)
    if request.method == "POST":
        user.edit_profil(request.POST["deskripsi"], user.foto_profil, request.POST["minat"])
        return redirect("users:profile")
    context = {"user" : user}
    return render(request, "users/edit.html", context)

def saldo(request):
    if request.method == "POST":
        saldo_dibeli = int(request.POST.get('tambah_saldo'))
        request.user.studentprofile.isi_saldo(saldo_dibeli)
        context = {
            "saldo": request.user.studentprofile.saldo,
            "tambah_saldo": saldo_dibeli,
        }
        return render(request, "users/saldo_success.html", context=context)
    context = {
        "saldo" : request.user.studentprofile.saldo
    }
    return render(request, "users/saldo.html", context=context)

users/templates/users/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <!-- External CSS -->
    <link rel="stylesheet" href="{% static 'users/css/base.css' %}">

    <!-- JQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script>

    <!-- Extra Font -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Playfair+Display&family=Rubik&display=swap" rel="stylesheet">
    
    <title>Kursus Plus</title>
  </head>
  <body class="body">

    <nav class="navbar smart-scroll navbar-expand-lg navbar-light h3 m-0">
        <div class="container">
            <a class="navbar-brand d-flex align-items-center" href="{% url 'dashboard:upcoming' %}">
                <img src="{% static 'users/img/logo.svg' %}" width="60" height="60" class="d-inline-block align-top" alt="">
                <h3 class="m-0 p-0 ml-3"><u>Kursus Plus</u></h3>
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
        
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'courses:courses_list' %}"><u>Courses</u></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'konten:listKonten' %}"><u>Konten</u></a>
                </li>
            </ul>
            <div class="nav-item dropdown border-1 bg-5 rounded">
                <div class="nav-link dropdown-toggle h4 m-0" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    {{request.user.username}}
                </div>
                <div class="dropdown-menu  dropdown-menu-right bg-3" aria-labelledby="navbarDropdown">
                    <div class="d-flex flex-column justify-content-center align-items-center">
                        <a class="dropdown-item" href="{% url 'users:profile' %}">Profil</a>
                        <a class="dropdown-item" href="{% url 'users:saldo' %}">Isi Saldo</a>
                        <div class="dropdown-divider"></div>
                        <a class="btn btn-danger w-75" href="{% url 'users:logout' %}">Logout</a>
                    </div>
                </div>
            </div>
            </div>
        </div>
      </nav>

      <div class="item-container container pt-3">
        {% block content %}
        {% endblock %}
      </div>



      <footer class="bg-2 p-2 text-light d-flex align-items-center justify-content-center h4 m-0">
            © Kursus Plus 2020
      </footer>







    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  
    <!-- External JS -->
    <script src="{% static 'users/js/base.js' %}"></script>

    </body>
</html>

users/templates/users/landing.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <!-- External CSS -->
    <link rel="stylesheet" href="{% static 'users/css/base.css' %}">

    <!-- JQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script>

    <!-- Extra Font -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Playfair+Display&family=Rubik&display=swap" rel="stylesheet">
    
    <title>Kursus Plus</title>
  </head>
  <body class="body">

    <div class="min-vh-100 p-2 beach-bg">
        <div class="d-flex justify-content-between align-items-center">
            <a class="navbar-brand d-flex align-items-center text-dark" href="#">
                <img src="{% static 'users/img/logo.svg' %}" width="60" height="60" class="d-inline-block align-top" alt="">
                <h3 class="m-0 p-0 ml-3"><u>Kursus Plus</u></h3>
            </a>

            <div>
                <a href="{% url 'users:register' %}">
                    <button class="btn btn-1 border-3">
                        Register
                    </button>
                </a>

                <a href="{% url 'users:login' %}">
                    <button class="btn btn-3 border-1">
                        Login
                    </button>
                </a>
            </div>
        </div>

        <div class="item-container-no-nav flex-column d-flex justify-content-center align-items-center">
            <h2 class="quote text-center quote-shadow">“Distance should not be a hassle for education.”</h2>
            <h3 class="quote text-center mb-4 quote-shadow">we agree.</h3>
            <a href="{% url 'users:register' %}">
                <button class="btn border-2 rounded p-2 btn-3 quote">
                        Daftar sekarang
                </button>
            </a>
        </div>
    </div>

    <div class="body-landing min-vh-100 p-3">
        <h2 class="text-center my-5">Mengapa Online Learning?</h2>

        <div class="row">
            <div class="col-lg-4 col-sm-12 mt-2">
                <div class="h-100 bg-3 border-1 rounded p-2 landing-card d-flex flex-column justify-content-center align-items-center">
                    <img class="m-3" src="{% static 'users/img/earth.svg' %}">
                    <h4>Terbuka</h4>
                    <p class="text-center">Baik berbeda kota, provinsi, atau bahkan berbeda pulau, kami percaya bahwa jarak bukan masalah untuk pendidikan di zaman kini.</p>
                </div>
            </div>
            <div class="col-lg-4 col-sm-12 mt-2">
                <div class="h-100 bg-3 border-1 rounded p-2 landing-card d-flex flex-column justify-content-center align-items-center">
                    <img class="m-3" src="{% static 'users/img/clock.svg' %}">
                    <h4>Fleksibel</h4>
                    <p class="text-center">Pengaturan waktu kapan anda ingin belajar adalah keputusan anda, bukan kami.</p>
                </div>
            </div>
            <div class="col-lg-4 col-sm-12 mt-2">
                <div class="h-100 bg-3 border-1 rounded p-2 landing-card d-flex flex-column justify-content-center align-items-center">
                    <img class="m-3" src="{% static 'users/img/hand.svg' %}">
                    <h4>Hemat</h4>
                    <p class="text-center">Tidak ada biaya transportasi, ruangan, atau infrastruktur, cukup membayar jasa pengajar saja.</p>
                </div>
            </div>
        </div>

        <h1 class="text-center mt-4">Daftar sekarang!</h1>
    </div>






        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

        <!-- External JS -->
        <script src="{% static 'users/js/base.js' %}"></script>

    </body>
</html>

users/templates/users/login.html
{% extends 'users/login_reg_base.html' %}
{% block content %}

<div class="d-flex justify-content-center align-items-center flex-column">
    {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{message.tags}} fade show" role="alert">
            {{message}}
        </div>
        {% endfor %}
    {% endif %}

    <div class="bg-3 border-1 p-4 rounded mt-2 login-form">
        <h3 class="text-center">Selamat datang kembali</h3>

        <form class="d-flex flex-column justify-content-center" action="{% url 'users:login' %}" method="POST">
            {% csrf_token %}
            <div class="form-group">
            <label for="name-in">Username</label>
            <input name="username" type="text" class="form-control" id="name-in" placeholder="Username">
            </div>
            <div class="form-group">
            <label for="pass-in">Password</label>
            <input name="password" type="password" class="form-control" id="pass-in" placeholder="Password">
            </div>
            <p>Belum punya akun? <a href="{% url 'users:register' %}">Register</a></p>
            <button type="submit" class="btn btn-1 border-2">Login</button>
        </form>
    </div>
</div>

{% endblock %}

users/templates/users/placeholder.html
{% extends 'users/base.html' %}
{% block content %}
<h1>Website coming soon :^)</h1>
{% endblock %}

users/templates/users/profile.html
{% extends 'users/base.html' %}
{% load static %}
{% block content %}
    <div class="d-flex justify-content-around">
        <h1>Edit profile untuk {{user.nama}}</h1>
        <div class="text-center">
            <h6><b>Assessment</b></h6>
            <h6><b>Untuk {{user.nama}}</b></h6>
        </div>
    </div>
    <div class="row">
        <div class="bg-5 border-1 p-3 rounded mb-4 col-md-7 col-sm-12 align-self-start">
            <div class="d-flex justify-content-around mt-2">
                <img src="{{user.foto_profil}}" width="130" height="130" class="d-inline-block align-top rounded-circle" alt="">
                <div class="text-center mt-4 mr-5">
                    <h4 class="mt-2"><b>Halo! Saya {{user.nama}}</b></h4>
                    <h4>{{user.user.email}}</h4>
                </div>
            </div>
            <div class="mt-4 ml-5">
                <p><b>Deskripsi :</b></p>
                <p>{{user.deskripsi}}</p>
                <p><b>Minat :</b></p>
                <p>{{user.bidang_minat}}</p>
                <a class="btn btn-primary w-100" href="{% url 'users:edit' %}">Edit</a>
            </div>


        </div>
        {% include 'users/profile_sidebar.html' %}

    </div>
{% endblock %}

users/templates/users/register.html
{% extends 'users/login_reg_base.html' %}
{% block content %}

<div class="d-flex justify-content-center align-items-center flex-column">
    {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{message.tags}} fade show" role="alert">
            {{message}}
        </div>
        {% endfor %}
    {% endif %}
    <div class="bg-3 border-1 p-4 rounded mt-2 login-form">
        <h3 class="text-center">Selamat datang di Kursus Plus</h3>
        
        <form method="POST" action="{% url 'users:register' %}" class="d-flex flex-column justify-content-center">
            {% csrf_token %}
            <div class="form-group">
            <label for="email-in">Email</label>
            <input name="email" type="text" class="form-control" id="email-in" placeholder="Email">
            </div>
            <div class="form-group">
            <label for="name-in">Username</label>
            <input name="username" type="text" class="form-control" id="name-in" placeholder="Username">
            </div>
            <div class="form-group">
            <label for="pass-in">Password</label>
            <input name="password1" type="password" class="form-control" id="pass-in" placeholder="Password">
            </div>
            <div class="form-group">
            <label for="pass2-in">Confirm Password</label>
            <input name="password2" type="password" class="form-control" id="pass2-in" placeholder="Password Confirm">
            </div>
            <p>Sudah punya akun? <a href="{% url 'users:login' %}">Login</a></p>
            <button type="submit" class="btn btn-1 border-2">Daftar</button>
        </form>
    </div>
</div>

{% endblock %}

users/templates/users/saldo.html
{% extends 'users/base.html' %}
{% load static %}
{% block content %}
    <div class="content">
        <h3>Saldo anda sekarang : <b><u>RP {{ saldo }},00</u></b>  </h3>
        <div class="row justify-content-between">
            <div class="bg-5 border-1 p-3 rounded my-2 col-lg-7 mt-3">
                <h3 class="mt-2"><b>Isi Saldo</b></h3>
                <div class="form-check">
                    <input class="form-saldo-input" type="radio" name="isi_saldo" id="saldo100k" value="100000">
                    <label class="m-2 h4" for="saldo100k"> Rp. 100.000,00 </label>
                    <br>
                    <input class="form-saldo-input" type="radio" name="isi_saldo" id="saldo200k" value="200000">
                    <label class="m-2 h4" for="saldo200k"> Rp. 200.000,00 </label>
                    <br>
                    <input class="form-saldo-input" type="radio" name="isi_saldo" id="saldo500k" value="500000">
                    <label class="m-2 h4" for="saldo500k"> Rp. 500.000,00 </label>
                    <br>
                    <input class="form-saldo-input" type="radio" name="isi_saldo" id="saldo1000k" value="1000000">
                    <label class="m-2 h4" for="saldo1000k"> Rp. 1.000.000,00 </label>
                </div>
                <!-- Button trigger modal -->
                <div class="row justify-content-center">
                    <button type="button" class="btn btn-primary mt-2" data-target="#exampleModal" onclick="modalClicked()">
                        Konfirmasi Pengisian Saldo
                    </button>
                </div>

                <!-- Modal -->
                <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                    <div class="modal-dialog modal-dialog-centered item" role="document">
                        <div class="row justify-content-center">
                            <div class="modal-content col-md-9 col-lg-6 bg-5">
                                <div class="modal-body text-center">
                                    <p>Anda akan mengisi Saldo sebesar</p>
                                    <p id="beli_saldo">Rp. 0</p>
                                    <p>Dengan mengisi saldo anda tidak bisa melakukan refund</p>
                                    <form method="POST" action="{% url 'users:saldo' %}">
                                        {% csrf_token %}
                                        <input type="hidden" name="tambah_saldo" id="tambah_saldo" value="0">
                                        <button type="submit" class="btn btn-info" >Setuju dan Isi Saldo</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script>
        function modalClicked() {
            var radio_button = window.document.getElementsByName('isi_saldo');
            for (i=0; i<radio_button.length;i++){
                if (radio_button[i].checked){
                    window.document.getElementById('tambah_saldo').value = radio_button[i].value
                    if (radio_button[i].value == 100000){
                        window.document.getElementById('beli_saldo').innerHTML = "Rp. 100.000,00";
                    }
                    else if (radio_button[i].value == 200000){
                        window.document.getElementById('beli_saldo').innerHTML = "Rp. 200.000,00";
                    }
                    else if (radio_button[i].value == 500000){
                        window.document.getElementById('beli_saldo').innerHTML = "Rp. 500.000,00";
                    }
                    else if (radio_button[i].value == 1000000){
                        window.document.getElementById('beli_saldo').innerHTML = "Rp. 1.000.000,00";
                    }
                }
            }
            $('#exampleModal').modal('toggle');
        }
    </script>


{% endblock %}

users/templates/users/saldo_success.html
{% extends 'users/base.html' %}
{% load static %}
{% block content %}
    <div class="content">
        <h3>Saldo anda sekarang : <b><u>RP {{ saldo }},00</u></b>  </h3>
        <div class="row justify-content-between">
            <div class="bg-5 border-1 p-3 rounded my-2 col-lg-7 mt-3">
                <h3 class="mt-2"><b>Isi Saldo</b></h3>
                <div class="form-check">
                    <input class="form-saldo-input" type="radio" name="isi_saldo" id="saldo100k" value="100000">
                    <label class="m-2 h4" for="saldo100k"> Rp. 100.000,00 </label>
                    <br>
                    <input class="form-saldo-input" type="radio" name="isi_saldo" id="saldo200k" value="200000">
                    <label class="m-2 h4" for="saldo200k"> Rp. 200.000,00 </label>
                    <br>
                    <input class="form-saldo-input" type="radio" name="isi_saldo" id="saldo500k" value="500000">
                    <label class="m-2 h4" for="saldo500k"> Rp. 500.000,00 </label>
                    <br>
                    <input class="form-saldo-input" type="radio" name="isi_saldo" id="saldo1000k" value="1000000">
                    <label class="m-2 h4" for="saldo1000k"> Rp. 1.000.000,00 </label>
                </div>
                <!-- Button trigger modal -->
                <div class="row justify-content-center">
                    <button type="button" class="btn btn-primary mt-2" data-target="#exampleModal" onclick="modalClicked()">
                        Konfirmasi Pengisian Saldo
                    </button>
                </div>

                <!-- Modal -->
                <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                    <div class="modal-dialog modal-dialog-centered item" role="document">
                        <div class="row justify-content-center">
                            <div class="modal-content col-md-9 col-lg-6 bg-5">
                                <div class="modal-body text-center">
                                    <p>Anda akan mengisi Saldo sebesar</p>
                                    <p id="beli_saldo">Rp. 0</p>
                                    <p>Dengan mengisi saldo anda tidak bisa melakukan refund</p>
                                    <form method="POST" action="{% url 'users:saldo' %}">
                                        {% csrf_token %}
                                        <input type="hidden" name="tambah_saldo" id="tambah_saldo" value="0">
                                        <button type="submit" class="btn btn-info" >Setuju dan Isi Saldo</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card text-center bg-success border-1 rounded my-5 col-lg-4 row align-self-center">
                <div class="card-body">
                    <h5>Pengisian saldo sebesar</h5>
                    <h5>{{ tambah_saldo }}</h5>
                    <h4><b><u>Berhasil</u></b></h4>
                </div>
            </div>
        </div>
    </div>

    <script>
        function modalClicked() {
            var radio_button = window.document.getElementsByName('isi_saldo');
            for (i=0; i<radio_button.length;i++){
                if (radio_button[i].checked){
                    window.document.getElementById('tambah_saldo').value = radio_button[i].value
                    if (radio_button[i].value == 100000){
                        window.document.getElementById('beli_saldo').innerHTML = "Rp. 100.000,00";
                    }
                    else if (radio_button[i].value == 200000){
                        window.document.getElementById('beli_saldo').innerHTML = "Rp. 200.000,00";
                    }
                    else if (radio_button[i].value == 500000){
                        window.document.getElementById('beli_saldo').innerHTML = "Rp. 500.000,00";
                    }
                    else if (radio_button[i].value == 1000000){
                        window.document.getElementById('beli_saldo').innerHTML = "Rp. 1.000.000,00";
                    }
                }
            }
            $('#exampleModal').modal('toggle');
        }
    </script>


{% endblock %}