courses/urls.py
from django.urls import path
from . import views

app_name = "courses"

urlpatterns = [
    path("", views.courses_list, name="courses_list"),
    path("<int:course_id>/subcourses", views.subcourses_list, name="subcourses_list"),
    path("subcourses/<int:subcourse_id>", views.subcourses_detail, name="subcourse_detail"),
    path("subcourses/<int:subcourse_id>/checkout", views.checkout, name="checkout"),
]

konten/urls.py
from django.urls import path
from . import views

app_name = "konten"

urlpatterns = [
    path("", views.viewKonten, name="listKonten"),
    path("add", views.addKonten, name="addKonten"),
    path("delete/<int:id>", views.deleteKonten, name="deleteKonten"),
    path("publish/<int:id>", views.publishKonten, name="publishKonten"),
]

kursus_plus/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("users.urls")),
    path("session/", include("video_call.urls")),
    path("courses/", include("courses.urls")),
    path("konten/", include("konten.urls")),
    path("dashboard/", include("dashboard.urls")),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("", views.landing, name="landing"),
    path("login", views.login_view, name="login"),
    path("register", views.register, name="register"),
    path("profile", views.profile, name="profile"),
    path("edit", views.edit, name="edit"),
    path("logout", views.logout_view, name="logout"),
    path("saldo/", views.saldo, name="saldo"),
]

courses/models.py
from django.db import models

# Create your models here.
class Course(models.Model):
    nama = models.CharField(max_length=255)
    deskripsi = models.CharField(max_length=2047)

class Subcourse(models.Model):
    harga = models.IntegerField()
    nama = models.CharField(max_length=255)
    deskripsi = models.CharField(max_length=2047)
    jam_dibutuhkan = models.IntegerField()
    course = models.ForeignKey(Course, on_delete=models.CASCADE)

class Transaksi(models.Model):
    waktu_pembelian = models.DateTimeField(auto_now_add=True)
    metode_pembayaran = models.CharField(max_length=63)
    jumlah_pembayaran = models.IntegerField()
    student_pembeli = models.ForeignKey("users.StudentProfile", on_delete=models.CASCADE)
    subcourse_dibeli = models.ForeignKey(Subcourse, on_delete=models.CASCADE)
    status = models.CharField(max_length=63)

class Appointment(models.Model):
    status = models.CharField(max_length=63)
    waktu_kursus = models.DateTimeField()
    kode_video_call = models.CharField(max_length=127)
    bagian_dari = models.ForeignKey(Transaksi, on_delete=models.CASCADE)

bintang_choices = [
    (1,1),
    (2,2),
    (3,3),
    (4,4),
    (5,5),
]

class Review(models.Model):
    nama = models.CharField(max_length=64)
    bintang = models.IntegerField(choices=bintang_choices)
    judul = models.CharField(max_length=64)
    deskripsi = models.TextField()
    subcourse = models.ForeignKey(Subcourse, on_delete=models.CASCADE, related_name='subcourse')

courses/forms.py
from django.forms import ModelForm, HiddenInput
from courses.models import Review

class Review_form(ModelForm):

    class Meta:
        model = Review
        fields = ('bintang', 'judul', 'deskripsi')
        widgets = {
            'nama' : HiddenInput(),
            'subcourse': HiddenInput(),
        }

courses/views.py
from django.shortcuts import render, redirect
from django.db.models import Avg
from courses.forms import Review_form
from users.models import StudentProfile
from courses.models import Course, Subcourse, Transaksi, Appointment, Review
from uuid import uuid4
from datetime import datetime
from django.contrib import messages

# Create your views here.
def courses_list(request):
    context = {
        "courses" : [
            (course, len(course.subcourse_set.all())) for course
            in Course.objects.all()
        ]
    }

    return render(request, "courses/courses_list.html", context=context)

def subcourses_list(request, course_id):
    context = {
        "subcourses" : Course.objects.get(id=course_id).subcourse_set.all()
    }

    return render(request, "courses/subcourses_list.html", context=context)

def subcourses_detail(request, subcourse_id):
    if request.method == "POST":
        can_review = request.user.studentprofile.transaksi_set.filter(subcourse_dibeli=subcourse_id).count()
        reviewed = Review.objects.all().filter(subcourse_id=subcourse_id).count()
        cannot_review = False
        if can_review < reviewed:
            cannot_review = True
        form_review = Review_form(request.POST)
        if cannot_review == True:
            messages.add_message(request, messages.ERROR, "Penambahan Review gagal, harap dicoba lagi")
            return redirect('courses:subcourse_detail', subcourse_id=subcourse_id)
        else :
            if form_review.is_valid():
                instance = form_review.save(commit=False)
                instance.nama = request.user.studentprofile.get_nama()
                instance.subcourse = Subcourse.objects.get(id=subcourse_id)
                instance.save()
            return redirect('courses:subcourse_detail', subcourse_id=subcourse_id)
    else :
        can_review = request.user.studentprofile.transaksi_set.filter(subcourse_dibeli=subcourse_id).count()
        reviewed = Review.objects.all().filter(subcourse_id=subcourse_id).count()
        cannot_review = False
        if can_review < reviewed:
            cannot_review = True
        reviews = Review.objects.filter(subcourse__id = subcourse_id)
        try :
            bintang_avg = round(list(reviews.aggregate(Avg('bintang')).values())[0], 2)
        except :
            bintang_avg = "X"
        form_review = Review_form()
        context = {
            "subcourse_id" : subcourse_id,
            "subcourse": Subcourse.objects.get(id=subcourse_id),
            "reviews": reviews,
            "form_review": form_review,
            "bintang_avg" : bintang_avg,
            "cannot_review": cannot_review,
        }
        return render(request, "courses/subcourse_detail.html", context=context)

def checkout(request, subcourse_id):
    if request.method == "POST":
        subcourse_dibeli = Subcourse.objects.get(id=subcourse_id)
        
        request.user.studentprofile.beli(
            subcourse_dibeli
        )
        messages.add_message(request, messages.SUCCESS, "Terima kasih atas pembelian sesi kursus!")

        return redirect("dashboard:upcoming")
    
    context = {
        "subcourse" : Subcourse.objects.get(id=subcourse_id),
        "nominal_after" : request.user.studentprofile.saldo - Subcourse.objects.get(id=subcourse_id).harga,
        
    }

    context["is_negatif"] = context["nominal_after"] < 0

    return render(request, "courses/checkout.html", context=context)

courses/templates/courses/checkout.html
{% extends 'users/base.html' %}
{% load static %}
{% block content %}

<link rel="stylesheet" href="{% static 'courses_css/courses.css' %}">

<!-- MODAL area -->
  <div class="modal fade" id="modalKonfirmasi" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header bg-1 text-light">
          <h5 class="modal-title" id="exampleModalLongTitle">Konfirmasi Pembelian</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body bg-5 text-center">
          <b>
              Dengan membeli sesi-sesi kursus, saldo dari akun anda akan dipotong,
              dan anda setuju bahwa <u>tidak ada refund</u> setelah pembelian
          </b>

          <p class="mt-3">
              <u>Klik setuju untuk konfirmasi pembelian</u>
          </p>
        </div>
        <div class="modal-footer bg-1 d-flex justify-content-center">
        <form method="POST" action="{% url 'courses:checkout' subcourse.id %}">
            {% csrf_token %}
          <button type="submit" class="btn btn-success">SETUJU</button>
        </form>
          <button type="button" class="btn btn-danger" data-dismiss="modal">CANCEL</button>
        </div>
      </div>
    </div>
  </div>

<!-- HTML area -->

<h2 class="text-center">Checkout subcourse Lorem Ipsum 1</h2>
<div class="row">
    <!-- Main box -->
    <div class="col-lg-8 col-sm-12">
        <div class="bg-5 border-1 p-2 rounded d-flex flex-column">

            <h3 class="text-center">Jadwal tersedia</h3>
            <p class="text-center"><u>Anda boleh memilih max. 4 jadwal</u></p>

            <table class="text-center jadwal-table">
                <tr>
                  <th></th>
                  <th>Senin</th>
                  <th>Selasa</th>
                  <th>Rabu</th>
                  <th>Kamis</th>
                  <th>Jumat</th>
                  <th>Sabtu</th>
                  <th>Minggu</th>
                </tr>
                <tr>
                    <td>08:00 - 09:00</td>
                    <td class="bg-secondary">
                    </td>
                    <td class="bg-secondary">
                    </td>
                    <td class="bg-secondary">
                    </td>
                    <td class="bg-secondary">
                    </td>
                    <td class="bg-secondary">
                    </td>
                    <td class="bg-secondary">
                    </td>
                    <td class="bg-secondary">
                    </td>
                </tr>
                <tr>
                    <td>09:00 - 10:00</td>
                    <td class="bg-secondary">
                    </td>
                    <td class="bg-secondary">
                    </td>
                    <td class="bg-secondary">
                    </td>
                    <td class="bg-secondary">
                    </td>
                    <td class="bg-secondary">
                    </td>
                    <td class="bg-secondary">
                    </td>
                    <td class="bg-secondary">
                    </td>
                </tr>
                <tr>
                    <td>10:00 - 11:00</td>
                    <td class="bg-secondary">
                    </td>
                    <td class="bg-secondary">
                    </td>
                    <td class="bg-secondary">
                    </td>
                    <td class="bg-secondary">
                    </td>
                    <td class="bg-secondary">
                    </td>
                    <td class="bg-secondary">
                    </td>
                    <td class="bg-secondary">
                    </td>
                </tr>
                <tr>
                    <td>11:00 - 12:00</td>
                    <td class="bg-secondary">
                    </td>
                    <td class="bg-available">
                    </td>
                    <td class="bg-available">
                    </td>
                    <td class="bg-available">
                    </td>
                    <td class="bg-available">
                    </td>
                    <td class="bg-available">
                    </td>
                    <td class="bg-secondary">
                    </td>
                </tr>

                <tr>
                    <td>12:00 - 13:00</td>
                    <td class="bg-secondary">
                    </td>
                    <td class="bg-available">
                    </td>
                    <td class="bg-available">
                    </td>
                    <td class="bg-available">
                    </td>
                    <td class="bg-available">
                    </td>
                    <td class="bg-available">
                    </td>
                    <td class="bg-secondary">
                    </td>
                </tr>

                <tr>
                    <td>13:00 - 14:00</td>
                    <td class="bg-secondary">
                    </td>
                    <td class="bg-secondary">
                    </td>
                    <td class="bg-secondary">
                    </td>
                    <td class="bg-secondary">
                    </td>
                    <td class="bg-secondary">
                    </td>
                    <td class="bg-secondary">
                    </td>
                    <td class="bg-secondary">
                    </td>
                </tr>

                <tr>
                    <td>14:00 - 15:00</td>
                    <td class="bg-secondary">
                    </td>
                    <td class="bg-secondary">
                    </td>
                    <td class="bg-secondary">
                    </td>
                    <td class="bg-secondary">
                    </td>
                    <td class="bg-secondary">
                    </td>
                    <td class="bg-secondary">
                    </td>
                    <td class="bg-secondary">
                    </td>
                </tr>

                <tr>
                    <td>15:00 - 16:00</td>
                    <td class="bg-secondary">
                    </td>
                    <td class="bg-available">
                    </td>
                    <td class="bg-available">
                    </td>
                    <td class="bg-secondary">
                    </td>
                    <td class="bg-available">
                    </td>
                    <td class="bg-available">
                    </td>
                    <td class="bg-available">
                    </td>
                </tr>

                <tr>
                    <td>16:00 - 17:00</td>
                    <td class="bg-secondary">
                    </td>
                    <td class="bg-secondary">
                    </td>
                    <td class="bg-secondary">
                    </td>
                    <td class="bg-secondary">
                    </td>
                    <td class="bg-secondary">
                    </td>
                    <td class="bg-secondary">
                    </td>
                    <td class="bg-secondary">
                    </td>
                </tr>

                <tr>
                    <td>17:00 - 18:00</td>
                    <td class="bg-secondary">
                    </td>
                    <td class="bg-secondary">
                    </td>
                    <td class="bg-secondary">
                    </td>
                    <td class="bg-secondary">
                    </td>
                    <td class="bg-secondary">
                    </td>
                    <td class="bg-secondary">
                    </td>
                    <td class="bg-secondary">
                    </td>
                </tr>

                <tr>
                    <td>18:00 - 19:00</td>
                    <td class="bg-secondary">
                    </td>
                    <td class="bg-secondary">
                    </td>
                    <td class="bg-secondary">
                    </td>
                    <td class="bg-secondary">
                    </td>
                    <td class="bg-secondary">
                    </td>
                    <td class="bg-secondary">
                    </td>
                    <td class="bg-secondary">
                    </td>
                </tr>

                <tr>
                    <td>19:00 - 20:00</td>
                    <td class="bg-secondary">
                    </td>
                    <td class="bg-secondary">
                    </td>
                    <td class="bg-secondary">
                    </td>
                    <td class="bg-secondary">
                    </td>
                    <td class="bg-secondary">
                    </td>
                    <td class="bg-secondary">
                    </td>
                    <td class="bg-secondary">
                    </td>
                </tr>

            </table>


        </div>
    </div>

    <!-- Konten terbaru box -->
    <div class="col-lg-4 col-sm-12">
        <div class="bg-5 border-1 p-2 rounded d-flex flex-column text-center align-items-center">
            <h3 class="my-2 text-center">Checkout</h3>

            <!-- Konten box -->
            <div class="d-flex align-items-center my-2">
            </div>

            <table class="table-harga">
                <tr>
                    <td class="table-harga cell-ket">Saldo anda:</td>
                    <td class="table-harga cell-harga">Rp {{request.user.studentprofile.saldo}},00</td>
                </tr>
                <tr>
                    <td class="table-harga cell-ket">Biaya kursus:</td>
                    <td class="table-harga cell-harga">Rp {{subcourse.harga}},00</td>
                </tr>
            </table>

            <div class="separator my-3"></div>

            <p class="p-0 m-0 mb-4">
                <b>
                    <u>
                    Nominal saldo setelah pembelian:
                    <br>
                    Rp {{nominal_after}},00
                    </u>
                </b>
            </p>

            {% if is_negatif %}
                Saldo tidak cukup!
                <br>
                silahkan isi saldo dahulu
            {% endif %}

            <a href="{% url 'users:saldo' %}">
                <u>Isi saldo</u>
            </a>

            <button class="btn btn-1 w-75" data-toggle="modal" data-target="#modalKonfirmasi"
                {% if is_negatif %}
                disabled
                {% endif %}
            >
                Konfirmasi Pembelian
            </button>

            <a class="btn btn-danger mt-2 w-75" href="{% url 'courses:subcourse_detail' subcourse.id %}">
                Cancel
            </a>

        </div>

        

    </div>
</div>

{% endblock %}

courses/templates/courses/courses_list.html
{% extends 'users/base.html' %}
{% load static %}
{% block content %}

<link rel="stylesheet" href="{% static 'courses_css/courses.css' %}">
<div class="row">
    <!-- Courses box -->
    <div class="col-lg-8 col-sm-12">
        <h2>Courses tersedia: </h2>

        <!-- Course individual box -->
        {% for course in courses %}
        <div class="bg-5 border-1 p-3 rounded my-2">
            <div class="d-flex align-items-center">
                <h2 class="p-0 m-0">{{course.0.nama}}</h2>
                <span class="ml-2">Terbagi menjadi {{course.1}} subcourse</span>
            </div>

            <p class="my-2">
                {{course.0.deskripsi}}
            </p>

            <a class="text-dark" href="{% url 'courses:subcourses_list' course.0.id %}">
                <h4 class="text-center"><u>Lihat semua Subcourse...</u></h4>
            </a>
        </div>
        {% endfor %}

        
    </div>

    <!-- Konten terbaru box -->
    <div class="col-lg-4 col-sm-12">
        
        {% include 'courses/konten_sidebar.html'  %}

    </div>
</div>

{% endblock %}

courses/templates/courses/konten_sidebar.html
<div class="bg-5 border-1 p-2 rounded d-flex flex-column">
    <h3 class="my-2 text-center">Konten Terbaru</h3>

    <!-- Konten box -->
    <div class="d-flex align-items-center my-2">
        <a href="{% url 'konten:listKonten' %}">
            <img class="konten-img-sm" src="https://via.placeholder.com/100">
        </a>
        <div class="ml-2">
            <a class="m-0 p-0 text-dark" href="{% url 'konten:listKonten' %}">
                <b><u>Lorem ipsum</u></b>
            </a>
            <p class="m-0 p-0">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do.
            </p>
        </div>
    </div>
    <div class="d-flex align-items-center my-2">
        <a href="{% url 'konten:listKonten' %}">
            <img class="konten-img-sm" src="https://via.placeholder.com/100">
        </a>
        <div class="ml-2">
            <a class="m-0 p-0 text-dark" href="{% url 'konten:listKonten' %}">
                <b><u>Lorem ipsum</u></b>
            </a>
            <p class="m-0 p-0">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do.
            </p>
        </div>
    </div>
    <div class="d-flex align-items-center my-2">
        <a href="{% url 'konten:listKonten' %}">
            <img class="konten-img-sm" src="https://via.placeholder.com/100">
        </a>
        <div class="ml-2">
            <a class="m-0 p-0 text-dark" href="{% url 'konten:listKonten' %}">
                <b><u>Lorem ipsum</u></b>
            </a>
            <p class="m-0 p-0">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do.
            </p>
        </div>
    </div>
    <div class="d-flex align-items-center my-2">
        <a href="{% url 'konten:listKonten' %}">
            <img class="konten-img-sm" src="https://via.placeholder.com/100">
        </a>
        <div class="ml-2">
            <a class="m-0 p-0 text-dark" href="{% url 'konten:listKonten' %}">
                <b><u>Lorem ipsum</u></b>
            </a>
            <p class="m-0 p-0">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do.
            </p>
        </div>
    </div>
</div>

courses/templates/courses/subcourse_detail.html
{% extends 'users/base.html' %}
{% load crispy_forms_filters %}

{% load static %}
{% block content %}

    <link rel="stylesheet" href="{% static 'courses_css/courses.css' %}">
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-danger fade show" role="alert">
                {{message}}
            </div>
        {% endfor %}
    {% endif %}

    <div class="row">
        <!-- Main box -->
        <div class="col-lg-8 col-sm-12">
            <h2 class="ml-1">Tentang subcourse {{subcourse.nama}}</h2>

            <!-- Subcourse detail box -->
            <div class="bg-5 border-1 p-3 rounded my-2">

                <p class="my-2">
                    {{subcourse.deskripsi}}
                </p>

                <div class="d-flex justify-content-between">
                    <div class="d-flex flex-column">
                        <p class="p-0 m-0">
                            Bagian dari course :
                            <a class="text-dark" href="{% url 'courses:subcourses_list' subcourse.course.id %}">
                                <u>{{subcourse.course.nama}}</u>
                            </a>
                        </p>

                        <p class="p-0 m-0">
                            Waktu dibutuhkan : <u>{{subcourse.jam_dibutuhkan}} Jam</u>
                        </p>
                        <div class="mt-3 mb-2">
                        <span class="h4 p-2 rounded bg-5 border-1">
                            Rp {{subcourse.harga}},00
                        </span>
                        </div>
                    </div>

                    <a class="btn btn-1 border-1" href="{% url 'courses:checkout' subcourse.id %}">
                        Lihat jadwal tersedia
                        <br>
                        dan
                        <br>
                        Checkout
                    </a>
                </div>

            </div>
            <div class="row ml-1 mt-4 justify-content-between mr-3">
                <h3>Rata-rata rating: {{ bintang_avg }}</h3>
                <button type="button" class="btn btn-1" data-toggle="modal" data-target="#exampleModal" data-whatever="@mdo"
                        {% if cannot_review %}
                        disabled
                        {% endif %}>
                    Add review</button>
                <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">

                    <div class="modal-dialog" role="document">
                        <div class="modal-content border-1">
                            <div class="modal-header">
                                <h5 class="modal-title " id="exampleModalLabel">Add Review</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">

                                <form action="{% url 'courses:subcourse_detail' subcourse_id%}" method="POST">
                                    <div class="modal-body">
                                        {% csrf_token %}
                                        {% load crispy_forms_tags %}
                                        {{ form_review|crispy }}
                                    </div>
                                    <div class="modal-footer">
                                        <button
                                                type="button"
                                                class="btn btn-secondary"
                                                data-dismiss="modal"
                                        >
                                            Close
                                        </button>
                                        <button type="submit" class="btn btn-primary">
                                            Add Review
                                        </button>
                                    </div>
                                </form>

                            </div>
                        </div>
                    </div>
                </div>

            </div>

            {% for review in reviews %}
                <div class="bg-5 border-1 p-3 rounded my-2">
                    <div class="d-flex justify-content-between align-items-center">
                        <h3 class="m-0 p-0">{{ review.judul }} by {{ review.nama }}</h3>
                        <div id="review_bintang">
                            {% if review.bintang == 5 %}
                                <img src="{% static 'courses_img/star.svg' %}">
                                <img src="{% static 'courses_img/star.svg' %}">
                                <img src="{% static 'courses_img/star.svg' %}">
                                <img src="{% static 'courses_img/star.svg' %}">
                                <img src="{% static 'courses_img/star.svg' %}">
                            {% elif review.bintang == 4 %}
                                <img src="{% static 'courses_img/star.svg' %}">
                                <img src="{% static 'courses_img/star.svg' %}">
                                <img src="{% static 'courses_img/star.svg' %}">
                                <img src="{% static 'courses_img/star.svg' %}">
                            {% elif review.bintang == 3 %}
                                <img src="{% static 'courses_img/star.svg' %}">
                                <img src="{% static 'courses_img/star.svg' %}">
                                <img src="{% static 'courses_img/star.svg' %}">
                            {% elif review.bintang == 2 %}
                                <img src="{% static 'courses_img/star.svg' %}">
                                <img src="{% static 'courses_img/star.svg' %}">
                            {% elif review.bintang == 1 %}
                                <img src="{% static 'courses_img/star.svg' %}">
                            {% endif %}
                        </div>
                    </div>
                    <p>{{ review.deskripsi }}</p>
                </div>
            {% endfor %}

        </div>

        <!-- Konten terbaru box -->
        <div class="col-lg-4 col-sm-12">
            {% include 'courses/konten_sidebar.html'  %}

        </div>
    </div>


{% endblock %}

courses/templates/courses/subcourses_list.html
{% extends 'users/base.html' %}
{% load static %}
{% block content %}

<link rel="stylesheet" href="{% static 'courses_css/courses.css' %}">
<div class="row">
    <!-- Courses box -->
    <div class="col-lg-8 col-sm-12">
        <h2>Subcourses untuk Course X: </h2>

        <!-- Course individual box -->
        {% for subcourse in subcourses %}
        <div class="bg-5 border-1 p-3 rounded my-2">
            
            <h2 class="p-0 m-0">{{subcourse.nama}}</h2>

            <p class="my-2">
                {{subcourse.deskripsi}}
            </p>

            <div class="d-flex justify-content-between align-items-center">
                <a class="text-dark" href="{% url 'courses:subcourse_detail' subcourse.id %}">
                    <h4 class="p-0 m-0">
                        <u><b>Lihat detail...</b></u>
                    </h4>
                </a>

                <div class="border-1 bg-5 p-1 rounded">
                    <h4 class="p-0 m-0">
                        Rp {{subcourse.harga}},00
                    </h4>
                </div>
            </div>
        </div>
        {% endfor %}
        
    </div>

    <!-- Konten terbaru box -->
    <div class="col-lg-4 col-sm-12">
        {% include 'courses/konten_sidebar.html'  %}
    </div>
</div>

{% endblock %}