dashboard/urls.py
from django.urls import path
from . import views

app_name = "dashboard"

urlpatterns = [
    path("", views.upcoming, name="upcoming")
]

kursus_plus/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("users.urls")),
    path("session/", include("video_call.urls")),
    path("courses/", include("courses.urls")),
    path("konten/", include("konten.urls")),
    path("dashboard/", include("dashboard.urls")),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("", views.landing, name="landing"),
    path("login", views.login_view, name="login"),
    path("register", views.register, name="register"),
    path("profile", views.profile, name="profile"),
    path("edit", views.edit, name="edit"),
    path("logout", views.logout_view, name="logout"),
    path("saldo/", views.saldo, name="saldo"),
]

video_call/urls.py
from django.urls import path
from . import views

app_name = "video_call"

urlpatterns = [
    path("<int:appointment_id>", views.sesi_kursus_view, name="sesi_kursus")
]

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from courses.models import Appointment
from users.models import StudentProfile

day = ['Senin', 'Selasa', 'Rabu', 'Kamis', 'Jumat', 'Sabtu', 'Minggu']
month = ['Januari', 'Februari', 'Maret', 'April', 'Mei', 'Juni', 'Juli', 'Agustus', 'September', 'Oktober', 'November', 'Desember']

def upcoming(request):
    if not request.user.is_authenticated:
        return redirect("users:login")
    if request.method == "POST":
        messages.add_message(request, messages.SUCCESS, "Pembelian sesi kursus berhasil!")

    user = StudentProfile.objects.get(user=request.user.id)
    context = {"apts" : [], "user" : user}
    for apt in user.get_upcoming_apt():
        nama_subcourse = apt.bagian_dari.subcourse_dibeli.nama
        apt_list = Appointment.objects.filter(bagian_dari=apt.bagian_dari).order_by("waktu_kursus")
        for i in range(apt_list.count()):
            if apt_list[i] == apt:
                sesi = "Sesi kursus ke-" + str(i+1) + " dari " + str(apt_list.count())
                break
        tanggal = str(day[apt.waktu_kursus.weekday()]) + ", " + str(apt.waktu_kursus.day) + ' ' + str(month[apt.waktu_kursus.month-1]) + ' ' + str(apt.waktu_kursus.year)
        waktu = str(apt.waktu_kursus.hour) + ":" + str(apt.waktu_kursus.minute) + " - " + str((apt.waktu_kursus.hour + 1) % 24) + ":" + str(apt.waktu_kursus.minute)
        context["apts"].append([nama_subcourse, sesi, tanggal, waktu, apt.id])
    return render(request, "dashboard/upcoming.html", context)

dashboard/templates/dashboard/upcoming.html
{% extends 'users/base.html' %}
{% load static %}
{% block content %}

<link rel="stylesheet" href="{% static 'dashboard/css/dashboard.css' %}">
<div class="row">
    <!-- Courses box -->
    <div class="col-lg-8 col-sm-12">

        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{message.tags}} fade show" role="alert">
                    {{message}}
                </div>
            {% endfor %}
        {% endif %}

        <h2>Selamat Datang,<br>{{user.nama}}</h2>

        <!-- Course individual box -->
        <div class="bg-5 border-1 p-3 rounded my-2">

            <div class="row">
                {% if apts %}
                    {% for appointment in apts %}
                    <div class="col-lg-12 col-sm-12">
                        <div class="bg-upcoming border-1 p-3 rounded my-2">
                            <div class="row">
                                <div class="col-lg-3 text-center">
                                    <img class="upcoming-img rounded-circle" src="https://via.placeholder.com/150">
                                </div>
                                <div class="col-lg-9">
                                    <div class="ml-3">
                                        <h3 class="m-0 p-0">
                                            {{appointment.0}}
                                        </h3>
                                        <p class="m-0 p-0">
                                            {{appointment.1}}
                                        </p>
                                        <p class="m-0 p-0 mt-1">
                                            {{appointment.2}}<br>
                                            {{appointment.3}}
                                        </p>
                                        <div class="row">
                                            <div class="col-md-6 mb-2">
                                                <a class="btn btn-light w-100" href="{% url 'video_call:sesi_kursus' appointment.4 %}">Join Video Call</a>
                                            </div>
                                            <div class="col-md-6">
                                                <a class="btn btn-danger w-100" href="#">Undur Jadwal</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %} 
                {% else %}
                    <div class="col-lg-12">
                        <p>Kamu tidak memiliki appointment, ayo daftar di subcourse yang tersedia</p>
                    </div>
                {% endif %}
                
            </div>
        </div>
        
    </div>

    <!-- Konten terbaru box -->
    <div class="col-lg-4 col-sm-12">
        {% include 'courses/konten_sidebar.html'  %}
    </div>
</div>

{% endblock %}